### ISSUE TITLE
PAM examples cant be git cloned from windows

### ISSUE THREAD

**Issue by garethahealy** [redhat-cop/businessautomation-cop#109]
@ippul ; if you try to clone the examples on a windows machine, you get:

```
"C:\Program Files\Git\bin\git.exe" checkout --progress --force -B master refs/remotes/origin/master
  ##[error]error: invalid path 'pam-quick-examples/dmn-example1/requests/com.redhat.cop.pam:dmn-example1-kjar:1.0.json'
  ##[error]The process 'C:\Program Files\Git\bin\git.exe' failed with exit code 128
```

Is it possible to change the JSON file name? I think its due to **:**

NOTE: although it only complains about this 1 file, I presume there are others.

**Comment by erouvas** [comment]
@garethahealy have you tried from a cygwin environment ?
