### ISSUE TITLE
Create README for this repo 

### ISSUE THREAD

**Issue by springdo** [redhat-cop/businessautomation-cop#116]
There is no proper README for this repo .... The landing page gives no clear guidance as to what kind of things can be found here etc. See https://github.com/redhat-cop/containers-quickstarts for a good idea of where to start. Happy to PR

**Comment by pamenon** [comment]
Thanks for raised that, this is a very new repo therefore we didn't have a readme yet.
I will put something as initial page, feel free to collaborate and PR that as well.

**Comment by garethahealy** [comment]
@pamenon ; think this can be closed now, right?
