### ISSUE TITLE
Add other CoP managers/core members to approvers/merges

### ISSUE THREAD

**Issue by garethahealy** [redhat-cop/businessautomation-cop#123]
Add managers/core members to the "maintainers" block in the org/config, so they can merge and its not just all on one person (i.e.: @pamenon )
- https://github.com/redhat-cop/org/blob/master/config.yaml#L278

Looking in mojo, not sure who that is:
- https://mojo.redhat.com/community/communities-at-red-hat/applications/business-automation-community-of-practice

Should also add the current commuters to the "members" block.

**Comment by garethahealy** [comment]
CC @pamenon

**Comment by garethahealy** [comment]
CC @ally-jarrett

**Comment by ally-jarrett** [comment]
@garethahealy I've got an issue open to be added to redhat-cop then I can get @pamenon to give me access

**Comment by ally-jarrett** [comment]
I've raised this: https://github.com/redhat-cop/org/pull/235

This PR add's all CoP managers globally. We can close this once merged.

**Comment by ally-jarrett** [comment]
PR approved, closing issue.
