### ISSUE TITLE
Add a test to execute the install.sh for eap-setup

### ISSUE THREAD

**Issue by garethahealy** [redhat-cop/businessautomation-cop#125]
Be good if we can execute the shell scripts as part of the CI.
- https://github.com/redhat-cop/businessautomation-cop/tree/master/pam-eap-setup

Creds to download PAM can be stored as GitHub secrets.

Think this sounds possible @erouvas ?

**Comment by garethahealy** [comment]
The same idea could also be applied to:
- https://github.com/redhat-cop/businessautomation-cop/tree/master/bcgithook

**Comment by erouvas** [comment]
Sounds very good indeed.
I was planning to integrate bcgithook installation and pam-eap-setup. Would probably make it easier for the CI as well.
