### ISSUE TITLE
write the pam-eap-setup summary output to a file

### ISSUE THREAD

**Issue by rafaeltuelho** [redhat-cop/businessautomation-cop#216]
Would be useful to have the provision script write the installation summary output to a file. This file can be used for further reference as an installation log.

**Comment by erouvas** [comment]
good idea

**Comment by erouvas** [comment]
Submitted PR: https://github.com/redhat-cop/businessautomation-cop/pull/222

**Comment by erouvas** [comment]
can we please close this issue? 
It has been addressed with PR mentioned above

**Comment by ally-jarrett** [comment]
fixed
