### ISSUE TITLE
Enable CI bot

### ISSUE THREAD

**Issue by garethahealy** [redhat-cop/businessautomation-cop#66]
@pabrahamsson ; can you enable the ci-bot for this repo? or even better, does @pamenon (owner of the repo) have permissions to do that?

**Comment by ally-jarrett** [comment]
@garethahealy assuming this can be closed?

**Comment by garethahealy** [comment]
@ally-jarrett ; nah, not been done yet.

**Comment by pamenon** [comment]
@garethahealy can we close this issue?
