### ISSUE TITLE
Is bdd-ui/maven-java-bdd-demo a submodule?

### ISSUE THREAD

**Issue by garethahealy** [redhat-cop/businessautomation-cop#67]
The following git file makes the mvn bits of bdd a submodule:
https://github.com/redhat-cop/businessautomation-cop/blob/master/.gitmodules

But looking at the code, it seems like it has been pushed normally (github shows a different icon for submodule directories which isn't shown here):
- https://github.com/redhat-cop/businessautomation-cop/tree/master/bdd-ui/maven-java-bdd-demo

So should it be a submodule or just as it is? i.e. remove the submodule config

cc @pamenon

**Comment by pamenon** [comment]
Yes, it's just as it is, only the pam projects should be a submodule to make easy to import to BC, I will remove it

**Comment by pamenon** [comment]
@garethahealy Thanks for removing it.
