### ISSUE TITLE
bdd-ui doesnt work on node 12.x

### ISSUE THREAD

**Issue by garethahealy** [redhat-cop/businessautomation-cop#83]
If you try to build the node bits with v12, you get lots of errors:
- https://github.com/redhat-cop/businessautomation-cop/tree/master/bdd-ui

Since I am not that clued up on node, do we know someone who could update it? maybe @finmahon ?

**Comment by finmahon** [comment]
@garethahealy 
The front end could be updated easily enough.  

However the back end is heavily dependent on nodegit which doesn't work with node 12 currently

https://github.com/nodegit/nodegit/issues/1680

There's also a further issue with nodegit in that it's not open source now (it was when this project was created)

So, this will only work on node 10 for now.

**Comment by garethahealy** [comment]
@finmahon ; following that issue, node12 is supported from this release:
- https://github.com/nodegit/nodegit/releases/tag/v0.25.0
