### ISSUE TITLE
Create a script to install PAM

### ISSUE THREAD

**Issue by garethahealy** [redhat-cop/businessautomation-cop#93]
The pam examples provide run.sh scripts, but they presume you've already got it installed. Would be nice if we can provide scripts to install/configure it, so people can run:

- build.sh
- install.sh
- run.sh

and it all works.

CC @ippul 

Related to:
- https://github.com/redhat-cop/businessautomation-cop/pull/92

**Comment by ippul** [comment]
@garethahealy agree that would be great.
The running instance is needed only if you want to run the example with remote configuration.
At moment I only specify you need a running pam instance in the README of each [example](https://github.com/redhat-cop/businessautomation-cop/tree/master/pam-quick-examples/dmn-example1#remote)

**Comment by garethahealy** [comment]
https://github.com/redhat-cop/businessautomation-cop/tree/master/pam-eap-setup already does this.
